import type { Metadata } from 'next';
import './globals.css';
import { Raleway } from 'next/font/google';
import { Header } from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`min-h-dvh bg-beige/20 bg-[url(/bg.png)] bg-cover bg-fixed bg-no-repeat antialiased md:bg-center ${raleway.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
